### PR TITLE
:bug: fix(update config nodemailer + update field model):

### LINKED ISSUE #72: Server: Update config nodemailer + flow API SignUp
## Changes 

- Move config `nodemailer` into config `app`

### PR DESCRIPTION
**Pull request by tunganh252**
## Update

- Get config nodemailer from config root (env)
- Add check null || undefined messageId when nodemail have an error occurred
- Clear some field in model have required, unique because It has validated with vcc-schema

Closes #72

### CODE REVIEW

File: apps/server/src/datasources/utils/controllers/nodemailer/sendMailTemplate.ts [hunk 1]
```diff
@@ -18,5 +18,5 @@ export async function sendEmailVerify(req: Request, email) {
       `,
   });
 
-  return { messageId: info.messageId || '' };
+  return { messageId: info?.messageId || '' };
```
Comment (khoaquocngo) [inline apps/server/src/datasources/utils/controllers/nodemailer/sendMailTemplate.ts:21]: I think I can write `{ messageId: info?.messageId }` because info?.messageId  ->  `Value` || `Undefined`

**Review by trungpham71198 — APPROVED** [review]
